ECommerce/Areas/Admin/Controllers/CategoryController.cs
using ECommerce.Data.DatabaseContext;
using ECommerce.Data.Entity;
using ECommerce.Repositary.Interface;
using ECommerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var listOfCategory = await _unitOfWork.CategoryRepository.GetAllAsync();
            return View(listOfCategory);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "Display Order Doesn't exactly match Name");
            }
            if (ModelState.IsValid)
            {
                await _unitOfWork.CategoryRepository.AddAsync(category);
                _unitOfWork.Save();
                TempData["Success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var FindCategory = await _unitOfWork.CategoryRepository.GetAsync(u => u.Id == id);

            if (FindCategory == null)
                return NotFound();

            return View(FindCategory);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.CategoryRepository.Update(category);
                _unitOfWork.Save();
                TempData["Success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var FindCategory = await _unitOfWork.CategoryRepository.GetAsync(u => u.Id == id);

            if (FindCategory == null)
                return NotFound();

            return View(FindCategory);
        }

        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeletePost(int? Id)
        {
            var FindCategory = await _unitOfWork.CategoryRepository.GetAsync(u => u.Id == Id);

            if (FindCategory == null)
            {
                return NotFound();
            }
            FindCategory.IsDeleted = true;

            _unitOfWork.CategoryRepository.Update(FindCategory);
            TempData["Success"] = "Category Deleted Successfully";
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

    }
}

ECommerce/Areas/Admin/Controllers/CompanyController.cs
using ECommerce.Data.Entity;
using ECommerce.Repositary.Interface;
using ECommerce.Utility;
using ECommerce.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var Company = await _unitOfWork.CompanyRepository.GetAllAsync();
            return View(Company);
        }

        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {

            if(id == null || id == 0)
            {
                return View(new Company());
            }
            else
            {
               var Company = await _unitOfWork.CompanyRepository.GetAsync(x => x.Id == id);
                return View(Company);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    await _unitOfWork.CompanyRepository.AddAsync(company);
                    _unitOfWork.Save();
                    TempData["success"] = "Company created successfully";
                }
                else
                {
                    _unitOfWork.CompanyRepository.Update(company);
                    _unitOfWork.Save();
                    TempData["success"] = "Company Updated successfully";
                }

                return RedirectToAction("Index");
            }

            return View(company);
        }

        #region Call API


        public async Task<IActionResult> GetAll()
        {
            var company = await _unitOfWork.CompanyRepository.GetAllAsync();
            return Json(new {Data = company});
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var findcompany = await _unitOfWork.CompanyRepository.GetAsync(x => x.Id == id);

            if(findcompany == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            findcompany.IsDeleted = true;
            _unitOfWork.CompanyRepository.Update(findcompany);
            _unitOfWork.Save();
            TempData["success"] = "Company Delete successfully";

            return Json(new { success = true, message = "Delete Successfully" });
        }
        #endregion
    }
}

ECommerce/Areas/Admin/Controllers/OrderController.cs
using ECommerce.Data.Entity;
using ECommerce.Repositary.Interface;
using ECommerce.Utility;
using ECommerce.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using Stripe.Climate;
using System.Security.Claims;

namespace ECommerce.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public OrderVm OrderVm { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int orderId)
        {
            OrderVm = new()
            {
                OrderHeader = await _unitOfWork.OrderHeaderRepository.GetAsync(x => x.Id == orderId
                ,include: "Applicationuser"),

                OrderDetail = await _unitOfWork.OrderDetail.GetAllAsyncWithExpression(x => x.OrderHeaderId == orderId
                , include: "Product")
            };

            return View(OrderVm);
        }

        [HttpPost]
        [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
        public async Task<IActionResult> UpdateOrderDetail()
        {

            var orderheaderformdb = await _unitOfWork.OrderHeaderRepository.GetAsync(x => x.Id == OrderVm.OrderHeader.Id);

            orderheaderformdb.Name = OrderVm.OrderHeader.Name;
            orderheaderformdb.PhoneNumber = OrderVm.OrderHeader.PhoneNumber;
            orderheaderformdb.City = OrderVm.OrderHeader.City;
            orderheaderformdb.PostalCode = OrderVm.OrderHeader.PostalCode;
            orderheaderformdb.State = OrderVm.OrderHeader.State;
            orderheaderformdb.StreetAddress = OrderVm.OrderHeader.StreetAddress;

            if (!string.IsNullOrEmpty(OrderVm.OrderHeader.Carrier))
            {
                orderheaderformdb.Carrier = OrderVm.OrderHeader.Carrier;
            }
            if (!string.IsNullOrEmpty(OrderVm.OrderHeader.TrackingNumber))
            {
                orderheaderformdb.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
            }

                _unitOfWork.OrderHeaderRepository.Update(orderheaderformdb);
                _unitOfWork.Save();
                TempData["Success"] = "Order Details Updated Successfully.";

                return RedirectToAction(nameof(Details), new { orderId = orderheaderformdb.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public  IActionResult StartProcessing()
        {
            _unitOfWork.OrderHeaderRepository.UpdateStatus(OrderVm.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public async Task<IActionResult> ShipOrder()
        {
            var orderheaderfromdb = await _unitOfWork.OrderHeaderRepository.GetAsync(x => x.Id == OrderVm.OrderHeader.Id);

            orderheaderfromdb.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
            orderheaderfromdb.Carrier = OrderVm.OrderHeader.Carrier;
            orderheaderfromdb.OrderStatus = SD.StatusShipped;
            orderheaderfromdb.ShippingDate = DateTime.Now;
            if(orderheaderfromdb.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderheaderfromdb.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }
            _unitOfWork.OrderHeaderRepository.Update(orderheaderfromdb);
            _unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public async Task<IActionResult> CancelOrder()
        {
            var orderheaderfromdb = await _unitOfWork.OrderHeaderRepository.GetAsync(x => x.Id == OrderVm.OrderHeader.Id);

            if(orderheaderfromdb.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderheaderfromdb.PaymentIntentId,
                };

                var service = new RefundService();

                Refund refund = service.Create(options);

                _unitOfWork.OrderHeaderRepository.UpdateStatus(orderheaderfromdb.Id, SD.StatusCancelled, SD.StatusRefunded);
            }
            else
            {
                _unitOfWork.OrderHeaderRepository.UpdateStatus(orderheaderfromdb.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Order Cancelled Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
        }

        [ActionName("Details")]
        [HttpPost]
        public async Task<IActionResult> Details_PAY_NOW()
        {

            OrderVm = new()
            {
                OrderHeader = await _unitOfWork.OrderHeaderRepository.GetAsync(x => x.Id == OrderVm.OrderHeader.Id
                , include: "Applicationuser"),

                OrderDetail = await _unitOfWork.OrderDetail.GetAllAsyncWithExpression(x => x.OrderHeaderId == OrderVm.OrderHeader.Id
                , include: "Product")
            };

            //STRIPE LOGIC
            var domain = Request.Scheme + "://" + Request.Host.Value + "/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={OrderVm.OrderHeader.Id}",
                CancelUrl = domain + $"admin/order/details?orderId={OrderVm.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in OrderVm.OrderDetail)
            {
                var sessionlineitem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100),
                        Currency="usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Title,
                        }
                    },
                    Quantity = item.Count,
                };

                options.LineItems.Add(sessionlineitem);
            }

            var service = new SessionService();
             Session session = service.Create(options);
            _unitOfWork.OrderHeaderRepository.UpdateStripePayment(OrderVm.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        [HttpGet]
        public async Task<IActionResult> PaymentConfirmation(int orderHeaderId)
        {
            var orderheaderfromdb = await _unitOfWork.OrderHeaderRepository.GetAsync(x => x.Id == orderHeaderId);

            if(orderheaderfromdb.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                var service = new SessionService();
                Session session = service.Get(orderheaderfromdb.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeaderRepository.UpdateStripePayment(orderHeaderId, session.Id, session.PaymentIntentId);
                    _unitOfWork.OrderHeaderRepository.UpdateStatus(orderHeaderId, orderheaderfromdb.OrderStatus, SD.PaymentStatusApproved);
                    _unitOfWork.Save();
                }
            }

            return View(orderHeaderId);
        }

            #region Api Calls

            [HttpGet]
        public async Task<IActionResult> GetAllAsync(string status)
        {
            IEnumerable<OrderHeader> orderheader;

            if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
            {
                orderheader = await _unitOfWork.OrderHeaderRepository.GetAllAsync(include: "Applicationuser");
            }
            else
            {
                var claimsIdetity = (ClaimsIdentity)User.Identity;
                var userid = claimsIdetity.FindFirst(ClaimTypes.NameIdentifier).Value;

                orderheader = await _unitOfWork.OrderHeaderRepository.GetAllAsyncWithExpression(x => x.ApplicationUserId == userid, 
                    include: "Applicationuser");
            }


            switch (status)
            {
                case "pending":
                    orderheader = orderheader.Where(x => x.PaymentStatus == SD.PaymentStatusDelayedPayment);
                        break;
                case "inprocess":
                    orderheader = orderheader.Where(x => x.OrderStatus == SD.StatusInProcess);
                        break;
                case "completed":
                    orderheader = orderheader.Where(x => x.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    orderheader = orderheader.Where(x => x.OrderStatus == SD.StatusApproved);
                    break;

                default:
                    break;
            }

            return Json(new {data = orderheader});
        }

        #endregion
    }
}

ECommerce/ViewComponents/ShoppingCartViewComponent.cs
using ECommerce.Repositary.Interface;
using ECommerce.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ECommerce.Web.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {

                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                    _unitOfWork.ShoppingCartRepository.GetAllWithExpression(u => u.ApplicationuserId == claim.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

ECommerce/Views/Shared/_Layout.cshtml
@using ECommerce.Utility
﻿@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark text-bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/EcoMartLogo.jpg" alt="EcoMart" style="width:30px"></img>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Order Managment</a>
                            </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>

                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                            </ul>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>

                    </ul>
                        <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-body text-muted">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by ECommerce.net
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ECommerce/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Error"]');
    </script>
}